# Generated by Django 4.1.1 on 2022-11-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0007_teacher_detail_alter_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='mobile_no',
        ),
        migrations.RemoveField(
            model_name='student',
            name='qualification',
        ),
        migrations.AddField(
            model_name='student',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
