# Generated by Django 4.1.1 on 2022-11-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0010_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Student Rating'},
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
