# Generated by Django 4.1.1 on 2022-11-04 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0012_remove_teacher_detail_teacher_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
