# Generated by Django 4.1.1 on 2022-11-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0014_studentfavouritecourse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentfavouritecourse',
            options={'verbose_name_plural': '8. Student Favourite Course'},
        ),
        migrations.AddField(
            model_name='student',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='student_profile_imgs/'),
        ),
    ]
