# Generated by Django 4.1.1 on 2022-11-06 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_main', '0016_alter_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_views',
            field=models.BigIntegerField(default=0),
        ),
    ]
